name: Check code style

on:
  push:
    branches:
      - prodik1
  pull_request:
    branches:
      - prodik1

jobs:
  checkcode:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Run StandardJS
        run: |
          npx standard